vich_uploader:
    db_driver: orm

    mappings:
        base_image:
            uri_prefix: /images/base
            upload_destination: '%kernel.project_dir%/public/images/base'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
